services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app-network

volumes:
  pgdata:
    driver: local
  bundle_path:

networks:
  app-network:
    driver: bridge
