version: "3.8"
x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/var/www/farma
    - bundle_path:/bundle
    - /dev/shm:/dev/shm
  tmpfs:
    - /tmp
  depends_on:
    - db
  networks:
    - app-network
  stdin_open: true
  tty: true

services:
  api:
    <<: *app
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
        " # Removing server.pid is technically a cleanup script
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  api-tests:
    <<: *app
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@db
    shm_size: "2gb" #set shared memory
    depends_on:
      - db

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: miniostorage
      MINIO_ROOT_PASSWORD: miniostorage
    command: server /data

volumes:
  pgdata:
    driver: local
  bundle_path:
  minio_data:

networks:
  app-network:
    driver: bridge
