default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] || Rails.application.credentials.database.host %>
  port: <%= ENV["DATABASE_PORT"] || Rails.application.credentials.database.port %>
  username: <%= ENV["DATABASE_USERNAME"] || Rails.application.credentials.database.username %>
  password: <%= ENV["DATABASE_PASSWORD"] || Rails.application.credentials.database.password %>

development:
  <<: *default
  database: farma_development

test:
  <<: *default
  database: farma_test

production:
  <<: *default
  database: farma_production
