name: Tests

on:
  workflow_call:
    secrets:
      RAILS_MASTER_KEY_TEST:
        required: true

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: [ "5432:5432" ]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install libpq-dev for postgres
        run: sudo apt-get -yqq install libpq-dev

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Compile assets
        env:
          SECRET_KEY_BASE_DUMMY: 1
        run: |
          bundle exec rails tailwindcss:build
          bundle exec rails assets:precompile

      - name: Prepare database
        run: |
          bundle exec rails db:test:prepare

      - name: Run tests
        # COVERAGE: true # Enable when we finish the tests for authentication
        run: |
          bundle exec rails test:all

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
