name: Tests

on:
  workflow_call:
    secrets:
      RAILS_MASTER_KEY_TEST:
        required: true

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
  DATABASE_URL: postgres://postgres:@db

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.4.2
      options: --network-alias testHost
    services:
      db:
        image: postgres
        ports: [ "5432:5432" ]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      chrome-server:
        image: selenium/standalone-chrome:134.0.6998.35-20250303
        ports: [ "4444:4444" ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install libpq-dev for postgres
        run: apt-get -yqq install libpq-dev

      - name: Cache bundle gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install bundle gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Compile assets
        env:
          SECRET_KEY_BASE_DUMMY: 1
        run: |
          bundle exec rails tailwindcss:build
          bundle exec rails assets:precompile

      - name: Prepare database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run tests
        env:
          SELENIUM_HOST: chrome-server
          SELENIUM_PORT: 4444
          TEST_APP_HOST: testHost
          # COVERAGE: true # Enable when we finish the tests for authentication
        run: |
          bundle exec rails test:all
