name: CI
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - update-ci

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    secrets: ${{ secrets.RAILS_MASTER_KEY_TEST }}

  code_quality:
    uses: ./.github/workflows/_linters.yml
