name: CI
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - update-ci

jobs:
  tests:
    uses: ./.github/workflows/reusable/tests.yml
  linters:
    uses: ./.github/workflows/reusable/linters.yml
